# Generated by Django 2.2.4 on 2020-10-06 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model',
            new_name='Movie',
        ),
    ]
